services:
  app:
    container_name: sample_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    environment:
      ## TODO: I want to inject environment variables reading env file. not want to write them in "docker-compose.yaml" directly 
      # APP_KEY value does not have important meaning, just for testing
      - APP_KEY=base64:bptEJNedFS9NMxyx+mVUjGY2M3SvcUT2+/LkGW0X8RY=

  web:
    container_name: nginx
    image: nginx:1.29.0-alpine # 公式イメージを指定
    ports:
      - 8080:80
    volumes:
      - ./src/public:/var/www/html/public:ro
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    container_name: mysql
    image: mysql:8.0 # 公式イメージを指定
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - ./docker/db/config/mysql.conf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_db

volumes:
  db-data:
